# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      mkdir $HOME/Downloads
      wget https://github.com/rsksmart/rskj/releases/download/IRIS-3.0.1/rskj-core-3.0.1-IRIS-all.jar -P $HOME/Downloads

      mkdir ~/.boltz
      cp boltz.gitpod.conf ~/.boltz/boltz.conf
      echo "agree color smart member eagle air march always tornado curious endless wise" > ~/.boltz/seed.dat
    command: yarn rsk:geth
  - init: |
        sudo apt install rsync --assume-yes
        sudo add-apt-repository -y ppa:ethereum/ethereum
        sudo apt-get update --assume-yes
        sudo apt-get install ethereum --assume-yes
    command: |
      echo 'web3.eth.defaultAccount = eth.accounts[0]'
      echo 'loadScript("/workspace/lnsovbridge/etherswap.js")'
      echo 'loadScript("/workspace/lnsovbridge/erc20swap.js")'
      echo 'loadScript("/workspace/lnsovbridge/erc20token.js")'
      geth attach http://127.0.0.1:4444/
    # fund metamask with regtest rsk - rpc url: https://4444-scarlet-kite-mva383vt.ws-us18.gitpod.io, chainid: 33
    # eth.sendTransaction({from:eth.accounts[1], to:'0x946b238f8Ead0170686b32b23070fF4BFB006D3B', value: web3.toWei(10, "ether"), gas:21000}); //fund your wallet
    # eth.sendTransaction({from:eth.accounts[1], to:'0xeCb6b2a431826634E36d2787016670EBd8AF5A9B', value: web3.toWei(10, "ether"), gas:21000}); //fund boltz signer
    # web3.eth.defaultAccount = eth.accounts[1]
    # erc20token.transfer('0x946b238f8Ead0170686b32b23070fF4BFB006D3B', web3.toWei(1000, "ether")); // erc20 tokens to metamask wallet
    # erc20token.transfer('0xeCb6b2a431826634E36d2787016670EBd8AF5A9B', web3.toWei(1000, "ether")); // erc20 tokens to boltz siger
    # add erc20 token address to metamask 0x271905cc3d21d8d11f3213e4130108295e578434
    # geth attach http://127.0.0.1:4444/ --jspath "/workspace/lnsovbridge" --exec 'loadScript("etherswap.js"); loadScript("erc20swap.js");' 
    # sleep 5
    #     web3.eth.defaultAccount = eth.accounts[0]
    #     loadScript("/workspace/lnsovbridge/erc20swap.js")
    #     loadScript("/workspace/lnsovbridge/etherswap.js")
    #     loadScript("/workspace/lnsovbridge/erc20token.js")
  - init: |
      yarn docker:regtest 
    command: >
      docker exec -it regtest bash
      alias lnclibtc2='docker exec -it regtest lncli --rpcserver=127.0.0.1:10011 --tlscertpath=/root/.lnd-btc/tls.cert --macaroonpath=/root/.lnd-btc/data/chain/bitcoin/regtest/admin.macaroon'
      echo 'lnclibtc2 command is ready'
  - init: |
      npm install
    command: |
      echo regtest rsk - rpc url: https://4444-${GITPOD_WORKSPACE_URL:8}, chainid: 33
      echo npm run dev
  #npm run dev
  - init: |
      git clone https://github.com/pseudozach/boltz-frontend.git /workspace/boltz-frontend
      export REACT_APP_BOLTZ_API=https://9001-${GITPOD_WORKSPACE_URL:8}
      gp env REACT_APP_BOLTZ_API=$REACT_APP_BOLTZ_API
      cd /workspace/boltz-frontend && npm i
    command: |
      echo npm run start  
  # btc-rbtc swapper
  - init: |
      git clone https://github.com/grmkris/btc-rbtc-swapper /workspace/btc-rbtc-swapper
      cd /workspace/btc-rbtc-swapper
    command: |
      echo hello-world


      
  # npm run start  
  # update frontend .env with current gitpod name e.g. REACT_APP_BOLTZ_API=https://9001-fuchsia-termite-wsc9g47t.ws-us18.gitpod.io/
     
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9001
    visibility: public
    onOpen: open-browser
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 4444
    visibility: public
    onOpen: open-browser